/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface UniversalAdapterInterface extends Interface {
  getFunction(
    nameOrSignature: "getData" | "isAvailable" | "setData"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DataStored"): EventFragment;

  encodeFunctionData(functionFragment: "getData", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isAvailable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setData",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setData", data: BytesLike): Result;
}

export namespace DataStoredEvent {
  export type InputTuple = [sender: AddressLike, key: string, value: BytesLike];
  export type OutputTuple = [sender: string, key: string, value: string];
  export interface OutputObject {
    sender: string;
    key: string;
    value: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UniversalAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): UniversalAdapter;
  waitForDeployment(): Promise<this>;

  interface: UniversalAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getData: TypedContractMethod<[key: string], [string], "view">;

  isAvailable: TypedContractMethod<[], [boolean], "view">;

  setData: TypedContractMethod<
    [key: string, value: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getData"
  ): TypedContractMethod<[key: string], [string], "view">;
  getFunction(
    nameOrSignature: "isAvailable"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setData"
  ): TypedContractMethod<[key: string, value: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "DataStored"
  ): TypedContractEvent<
    DataStoredEvent.InputTuple,
    DataStoredEvent.OutputTuple,
    DataStoredEvent.OutputObject
  >;

  filters: {
    "DataStored(address,string,bytes)": TypedContractEvent<
      DataStoredEvent.InputTuple,
      DataStoredEvent.OutputTuple,
      DataStoredEvent.OutputObject
    >;
    DataStored: TypedContractEvent<
      DataStoredEvent.InputTuple,
      DataStoredEvent.OutputTuple,
      DataStoredEvent.OutputObject
    >;
  };
}
