/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EthereumConfig } from "./EthereumConfig";
export type { SepoliaConfig } from "./SepoliaConfig";
